SELECT
    COLUMN_NAME,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_KEY,
    COLUMN_DEFAULT,
    EXTRA
FROM
    INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_SCHEMA = DATABASE() -- Use the currently selected database (passed as argument)
    AND TABLE_NAME = 'Books'
ORDER BY
    ORDINAL_POSITION;

